networks:
  virtual:
    driver: bridge

services:
  database:
    image: mysql:debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password 
    volumes:
      - db:/var/lib/mysql
    networks:
      - virtual

volumes:
  db: